### PR TITLE
[im-t2624]: Add Barefoot and Interface Masters SONiC related packages.

### PR DESCRIPTION
**Pull request by YuriiHordynskyi**
@AndriiKit, please review as well

### CODE REVIEW

**Comment by vitalivanov** [comment]
@YuriiHordynskyi @AndriiKit i think we need to put into commit message hash id from what packages were created.
for example , in case of bk/bu it should be master branch and commit id :
78c8289e5ad5727e92ee291ad12d80f7fb0cd502

Later on we can identify packages and what is inside this way.

Same should be done for sde and other packages.

@YuriiHordynskyi please do

**Comment by YuriiHordynskyi** [comment]
> @YuriiHordynskyi @AndriiKit i think we need to put into commit message hash id from what packages were created.
> for example , in case of bk/bu it should be master branch and commit id :
> 78c8289e5ad5727e92ee291ad12d80f7fb0cd502
> 
> Later on we can identify packages and what is inside this way.
> 
> Same should be done for sde and other packages.
> 
> @YuriiHordynskyi please do

ok

**Comment by YuriiHordynskyi** [comment]
Added imt-sdk and bfn sde branches details:
```
[im-t2624]: Add Barefoot and Interface Masters SONiC related packages.
    imt-sdk:
        branch: master
        commit: 78c8289e5ad5727e92ee291ad12d80f7fb0cd502
    bfn-sde:
        branch: master
        commit: d0b5d285ef229ec5029a6ab78fe326e83bb5ced2

```

**Comment by AndriiKit** [comment]
Small remark: the name of barefoot SDE repo is "bf-sde"

**Review by vitalivanov — APPROVED** [review]

**Review by AndriiKit — APPROVED** [review]

**Pull request merged**
